# Generated by Django 5.2.5 on 2025-08-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
