# Generated by Django 5.2.5 on 2025-08-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0002_rename_update_at_package_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='processing', max_length=20),
        ),
    ]
