# Generated by Django 5.2.5 on 2025-08-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.CharField(default='unknown2', max_length=50),
        ),
    ]
